---
# =============================================================================
# PolicyException: Nvidia Device Plugin
# =============================================================================
# nvidia-device-plugin DaemonSet runs as root to access /dev/nvidia* devices
# and configure GPU resources on the node.
# =============================================================================
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: nvidia-exceptions
  namespace: nvidia-device-plugin
spec:
  exceptions:
    - policyName: require-non-root-user
      ruleNames:
        - check-runasnonroot
    - policyName: disallow-privileged-containers
      ruleNames:
        - privileged-containers
    - policyName: require-resource-limits
      ruleNames:
        - validate-resources
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - nvidia-device-plugin
