---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: tetragon-exceptions
  namespace: kube-system
spec:
  exceptions:
    - policyName: disallow-privileged-containers
      ruleNames:
        - privileged-containers
    - policyName: disallow-host-namespaces
      ruleNames:
        - host-namespaces
    - policyName: require-non-root-user
      ruleNames:
        - check-runasnonroot
    - policyName: require-resource-limits
      ruleNames:
        - validate-resources
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system
          selector:
            matchLabels:
              app.kubernetes.io/name: tetragon