---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    app.kubernetes.io/name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: thor
      securityContext:
        fsGroup: 568
      containers:
        - name: sonarr
          image: ghcr.io/hotio/sonarr:release
          env:
            - name: PUID
              value: "568"
            - name: PGID
              value: "568"
            - name: TZ
              value: "Asia/Kolkata"
          ports:
            - name: webui
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: sonarr-config
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - NET_RAW
                - NET_ADMIN
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /ping
              port: 8989
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 8989
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: media-configs
        - name: data
          persistentVolumeClaim:
            claimName: media-data
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
  labels:
    app.kubernetes.io/name: sonarr
spec:
  selector:
    app.kubernetes.io/name: sonarr
  ports:
    - name: webui
      port: 8989
      targetPort: 8989
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: sonarr
  namespace: media
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - "sonarr.k8s.darktang3nt.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: sonarr
          port: 8989
          group: ""
          kind: Service
