---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Grafana"
    gethomepage.dev/description: "Metrics & log dashboards"
    gethomepage.dev/group: "Observability"
    gethomepage.dev/icon: "grafana.png"
    gethomepage.dev/href: "https://grafana.k8s.darktang3nt.cloud"
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "grafana.k8s.darktang3nt.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kube-prometheus-stack-grafana
          namespace: monitoring
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Prometheus"
    gethomepage.dev/description: "Metrics collection & alerting"
    gethomepage.dev/group: "Observability"
    gethomepage.dev/icon: "prometheus.png"
    gethomepage.dev/href: "https://prometheus.k8s.darktang3nt.cloud"
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "prometheus.k8s.darktang3nt.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-prometheus
          namespace: monitoring
          port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Alertmanager"
    gethomepage.dev/description: "Alert routing & silencing"
    gethomepage.dev/group: "Observability"
    gethomepage.dev/icon: "alertmanager.png"
    gethomepage.dev/href: "https://alertmanager.k8s.darktang3nt.cloud"
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "alertmanager.k8s.darktang3nt.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-alertmanager
          namespace: monitoring
          port: 9093
