---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracearr-httproute
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/darktang3nt69/homelab-gitops
    targetRevision: main
    path: infrastructure/tracearr
  destination:
    server: https://kubernetes.default.svc
    namespace: tracearr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
