---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-argocd-token
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homepage-argocd-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homepage
        property: argo-cd
